### PR TITLE
Glucose range display fixes

### LINKED ISSUE #91: Suggested blood glucose ranges
We should make a better description of blood glucose ranges suggested by different organizations. I know full titles are difficult to fit in UI design but I also believe abbreviation like ADA, AACE, UK Nice is not friendly to those who are not in US or UK. 

Also I'm not pretty sure if blood glucose ranges differs for people in different regions. For example TDA suggests to keep a 60-110mg/dl fasting glucose and < 140mg/dl glucose for 2 hours after meal, which looks quite different to what ADA and AACE suggests.

### LINKED ISSUE #289: Preferred range not displayed in Settings when selected
(originated from issue #288)

In Settings screen, the Preferred range does not display what's been selected, nor if that's remembered correctly. Any change in units may also fail since the Min and Max value don't change / remain grayed out when selecting Custom range.

### LINKED ISSUE #363: GlucoseRanges: Unaccessible 'blue' color value for 'ADA' preffered Range
Hi, 

I've already noticed that every value smaller than `70` would return `purple` so it won't return in any case`blue` color value for `ADA` preferred range, because conditional for this expects values lower than `70` which is as already reserved.

Here is an interesting part of code: 
```
 if (reading < 70) {
            return "purple";
        } else if (reading > 200) {
            return "red";
        } else if (reading > 70 | reading < 200) {
            // if not check with custom ranges
            switch (preferredRange) {
                case "ADA":
                    if (reading >= 70 & reading <= 180) {
                        return "green";
                    } else if (reading < 70) {
                        return "blue";
                    } else if (reading > 180) {
                        return "orange";
                    }
```

Check this code for `69`, `70` and `71` if that what was said is still not clear.

Cheers!

### PR DESCRIPTION
**Pull request by riskysnail**
* display both date and time for last reading in overview
* display the preferred range choice in preferences. Closes #289
* updates to GlucoseRanges. range presets are now displayed in user preferences as they are selected. Resolves #91
* change minimum glucose ranges for ADA and UK NICE presets. Closes #363

### CODE REVIEW

**Comment by riskysnail** [comment]
Do I need to do anything about the coveralls check fail?

**Comment by emartynov** [comment]
Sorry a lot for the delay with answer. I will try today to clean up warnings and finish the review.

Thank you for the contribution!

File: app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java [hunk 1]
```diff
@@ -53,56 +61,57 @@ void setPreferredRange(String preferredRange) {
...
+    public static int getPresetMin(String preset) {
+        switch (preset) {
+            case ADA:
+                return ADA_MIN;
+            case AACE:
+                return AACE_MIN;
+            case UKNICE:
+                return UKNICE_MIN;
+            default:
+                return ADA_MIN;
```
Comment (emartynov) [inline app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java:81]: Why ADA is selected as default?

File: app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java [hunk 2]
```diff
@@ -53,56 +61,57 @@ void setPreferredRange(String preferredRange) {
...
 
     @VisibleForTesting
     void setCustomMax(int customMax) {
-        this.customMax = customMax;
+        this.userMax = customMax;
+    }
+
+    public static int getPresetMin(String preset) {
+        switch (preset) {
+            case ADA:
```
Comment (emartynov) [inline app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java:74]: Super minor: You can combine with `default` case

File: app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java [hunk 3]
```diff
@@ -53,56 +61,57 @@ void setPreferredRange(String preferredRange) {
...
+    public static int getPresetMax(String preset) {
+        switch (preset) {
+            case ADA:
+                return ADA_MAX;
+            case AACE:
+                return AACE_MAX;
+            case UKNICE:
+                return UKNICE_MAX;
+            default:
+                return ADA_MAX;
```
Comment (emartynov) [inline app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java:94]: Same question

**Review by emartynov — APPROVED** [review]
Looks good to me. Just one question about ADA is the default.

File: app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java (hunk 1 above)
Comment (riskysnail) [reply app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java:81]: It seemed reasonable. The default is only returned when the preset string given is not a known preset. It may be preferable to raise an error instead.

File: app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java (hunk 2 above)
Comment (riskysnail) [reply app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java:74]: Perhaps that is a better solution to the question below. Remove one of the cases and use default instead?

File: app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java (hunk 1 above)
Comment (emartynov) [reply app/src/main/java/org/glucosio/android/tools/GlucoseRanges.java:81]: Oke, clear

**Comment by emartynov** [comment]
Would be super nice if we write some tests for these changes.

Also, from the overall overview, the `GlucoseRanges` has two responsibilities now:

1. Keep user input
2. Constant class for ranges

It would be preferable to split them. Maybe in the future.

**Comment by riskysnail** [comment]
I agree about GlucoseRanges. I'm thinking about creating a new class to handle the formatting of glucose readings (auto-converting to the preferred unit, potentially adding colorblind symbols for #178). This could be a good candidate to move the colorFromReading and stringToColor functions.

**Comment by ghost** [comment]
@riskysnail what is status now? are you going to rearrange this code as you suggested in last commit?
